version: "3.8"
services:
  markitdown_mcp:
    image: evolutta/markitdown-mcp:1.0
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    command: --sse --host 0.0.0.0 --port 3001
    networks:
      - network_swarm_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
networks:
  network_swarm_public:
    name: network_swarm_public
    external: true
